apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "zerotierrouter.fullname" . }}
  {{ - if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
  {{ - end }}
data:
  ZT_IFNAME: {{ .Values.config.internalInterfaceName | quote }}
  ZT_ENABLE_FORWARD: {{ .Values.config.enableForwarding | quote }}
  ZT_ENABLE_MASQUERADE: {{ .Values.config.enableMasquerade | quote }}
