apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "zerotierrouter.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  ZT_IFNAME: {{ .Values.config.internalInterfaceName | quote }}
  ZT_ENABLE_FORWARD: {{ .Values.config.enableForwarding | quote }}
  ZT_ENABLE_MASQUERADE: {{ .Values.config.enableMasquerade | quote }}
