{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "zerotierrouter.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.storage.storageClass | quote }}
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}
