{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "zerotierrouter.fullname" . }}
  {{ - if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
  {{ - end }}
  labels:
  {{- with .Values.storage.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.storage.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass | quote }}
  {{- end }}
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}
