apiVersion: v1
kind: Secret
metadata:
  name: {{ template "zerotierrouter.fullname" . }}
  namespace: {{ .Release.Namespace }}
stringData:
  ZT_NETWORKS: {{ .Values.config.networkIds | quote }}
  ZT_ID_PUBLIC: {{ .Values.config.identityPublic | quote }}
  ZT_ID_SECRET: {{ .Values.config.identitySecret | quote }}
