apiVersion: v1
kind: Secret
metadata:
  name: {{ template "zerotierrouter.fullname" . }}
  {{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
  {{- end }}
  labels:
  {{- with .Values.secret.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.secret.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  ZT_NETWORKS: {{ .Values.config.networkIds | quote }}
  ZT_ID_PUBLIC: {{ .Values.config.identityPublic | quote }}
  ZT_ID_SECRET: {{ .Values.config.identitySecret | quote }}
