global:
  namespace: ""

image:
  repository: ghcr.io/pmit-pro/zerotier-router
  tag: latest
  pullPolicy: Always

config:
  internalInterfaceName: ""
  enableForwarding: true
  enableMasquerade: true
  networkIds: ""
  identityPublic: ""
  identitySecret: ""
  runPrivileged: false

secret:
  annotations: {}
  labels: {}

storage:
  enabled: true
#  storageClass: ""
  accessMode: ReadWriteOnce
  size: 20Mi
  annotations: {}
  labels: {}

deployment:
  replicas: 1
  annotations: {}
  podAnnotations: {}
  labels: {}
  podLabels: {}